final products = [
  {
    'id': '0',
    'title': 'Red Magic S9',
    'price': 30000.00,
    'imageUrl': 'assets/images/redmagic_S9.png',
    'company': 'Republic of Gamers',
    'sizes': [16, 32],
  },
  {
    'id': '1',
    'title': 'ROG Phone 8',
    'price': 35540.00,
    'imageUrl': 'assets/images/rogphone8.png',
    'company': 'Republic of Gamers',
    'sizes': [8, 12, 24],
  },
  {
    'id': '2',
    'title': 'ROG Phone Ultimate',
    'price': 32999.00,
    'imageUrl': 'assets/images/rogphone_ult.png',
    'company': 'Republic of Gamers',
    'sizes': [8, 12, 24],
  },
  {
    'id': '3',
    'title': 'Samsung Galaxy',
    'price': 28999.00,
    'imageUrl': 'assets/images/samsung_galaxy.png',
    'company': 'Samsung',
    'sizes': [8, 16, 32],
  },
];

final laptops = [
  {
    'id': '0',
    'title': 'Acer 1',
    'price': 40000.00,
    'imageUrl': 'assets/images/Acer_1.png',
    'imageUrl2': 'assets/images/Acer_2.png',
    'imageUrl3': 'assets/images/Acer_3.png',
    'company': 'Acer',
    'sizes': [8, 16, 32],
  },
  {
    'id': '1',
    'title': 'Asus 1',
    'price': 40000.00,
    'imageUrl': 'assets/images/Asus_1.png',
    'imageUrl2': 'assets/images/Asus_2.png',
    'imageUrl3': 'assets/images/Asus_3.png',
    'company': 'Asus',
    'sizes': [8, 16, 32],
  },
  {
    'id': '2',
    'title': 'MSI Katana',
    'price': 40000.00,
    'imageUrl': 'assets/images/MSI_Katana_1.png',
    'imageUrl2': 'assets/images/MSI_Katana_2.png',
    'imageUrl3': 'assets/images/MSI_Katana_3.png',
    'company': 'MSI',
    'sizes': [8, 16, 32],
  },
  {
    'id': '3',
    'title': 'Razer Blade',
    'price': 40000.00,
    'imageUrl': 'assets/images/RazerBlade_1.png',
    'imageUrl2': 'assets/images/RazerBlade_2.png',
    'imageUrl3': 'assets/images/RazerBlade_3.png',
    'company': 'Razer Blade',
    'sizes': [8, 16, 32],
  },
];

final pcs = [
  {
    'id': '0',
    'title': 'Periphio Elemental Terra',
    'price': 40000.00,
    'imageUrl': 'assets/images/elemental_terra_pc.png',
    'imageUrl2': '',
    'imageUrl3': '',
    'company': 'Periphio',
    'sizes': [8, 16, 32],
  },
  {
    'id': '1',
    'title': 'Periphio Fortress',
    'price': 40000.00,
    'imageUrl': 'assets/images/fortress_pc.png',
    'imageUrl2': '',
    'imageUrl3': '',
    'company': 'Periphio',
    'sizes': [8, 16, 32],
  },
  {
    'id': '2',
    'title': 'Periphio Shadow Reaper',
    'price': 40000.00,
    'imageUrl': 'assets/images/shadow_reaper_pc.png',
    'imageUrl2': 'assets/images/MSI_Katana_2.png',
    'imageUrl3': 'assets/images/MSI_Katana_3.png',
    'company': 'Periphio',
    'sizes': [8, 16, 32],
  },
  {
    'id': '3',
    'title': 'Periphio Portal Wrap',
    'price': 40000.00,
    'imageUrl': 'assets/images/portal_wrap_pc.png',
    'imageUrl2': 'assets/images/RazerBlade_2.png',
    'imageUrl3': 'assets/images/RazerBlade_3.png',
    'company': 'Periphio',
    'sizes': [8, 16, 32],
  }
];
